#!/usr/bin/env bash
DIR="$(dirname "$(readlink -f "$0")")"
cd $DIR/wkhtmltox
zephir build
echo "extension=/vagrant/wkhtmltox/ext/modules/wkhtmltox.so" | sudo tee /etc/php5/mods-available/wkhtmltox.ini
php -m