---
server:
    install: '1'
    timezone: Europe/Brussels
    locale: nl_NL.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: phphtmltox, ip: 192.168.33.99, memory: '2048', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt]
composer:
    install: '1'

