---
- name: Install dependencies
  apt: pkg={{ item }} state=latest
  with_items:
    - re2c
    - libpcre3-dev
    - libjson0
    - libjson0-dev
  become: yes
  become_user: root

- name: Download composer package
  shell: composer global require phalcon/zephir
  become: yes
  become_user: vagrant

- name: Add Composer bin directory to $PATH
  lineinfile: dest=/etc/environment state=present backrefs=yes regexp='PATH=(["]*)((?!.*?{{ item }}).*?)(["]*)$' line="PATH=\1\2:{{ item }}\3"
  with_items:
    - "~/.composer/vendor/bin"

- name: Make Zephir installer executable
  file: path=/home/vagrant/.composer/vendor/phalcon/zephir/install mode=0755

- name: Install Zephir
  shell: ./install chdir=/home/vagrant/.composer/vendor/phalcon/zephir
  become: yes
  become_user: root
